#theme: jekyll-theme-minima
remote_theme: chris4jahn/CloudCoffeebreak
title: Cloud Coffeebreak
author: Christian Forjahn
description: Dein Stopp für die Kaffeepause
### weitere Theme-bezogene Einstellungen
#background: '/PATH_TO_IMAGE'
linkedin_username: christian-forjahn