#remote_theme: chris4jahn/Cloud-Coffeebreak
#theme: jekyll-theme-clean-blog
title: Cloud Coffeebreak
author: Christian Forjahn
description: Your Tech Snacks for the Coffeebreak!
### weitere Theme-bezogene Einstellungen
#background: '/PATH_TO_IMAGE'
linkedin_username: christian-forjahn
#google_analytics: G-1SDL4WXVJC
relative_links:
  enabled:     true
  collections: true
