#theme: jekyll-theme-minima
remote_theme: chris4jahn/Cloud-Coffeebreak
title: Cloud Coffeebreak
author: Christian Forjahn
description: Deine Tech Snacks für die Kaffeepause!
### weitere Theme-bezogene Einstellungen
#background: '/PATH_TO_IMAGE'
linkedin_username: christian-forjahn
relative_links:
  enabled:     true
  collections: true
